apiVersion: v1
kind: Service
metadata:
  name: azure-demo-repo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: azure-demo-repo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-demo-repo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-demo-repo
  template:
    metadata:
      labels:
        app: azure-demo-repo
    spec:
      containers:
      - name: azure-demo-repo
        image: adrianb17/azure-demo-repo:latest
        ports:
        - containerPort: 8080
